//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VareeWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductDetail
    {
        public int ProductID { get; set; }
        public string ProductName { get; set; }
        public string Description { get; set; }
        public int DealOfTheDay { get; set; }
        public System.DateTime DealEndsIn { get; set; }
        public decimal Price { get; set; }
        public decimal MRP { get; set; }
        public int DiscountPercentage { get; set; }
        public string AvailabilityStatus { get; set; }
        public int Stock { get; set; }
        public string ImageURL { get; set; }
    }
}
